import asyncio
import os
import sys

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from app.auth.service import _seed_admin
from app.database import _get_sessionmaker, init_db
from app.models import Program, University

MOCK_UNIVERSITIES = [
    {
        "id": "ui",
        "name": "Universitas Indonesia",
        "programs": [
            {"name": "Kedokteran", "score": 750.5},
            {"name": "Kedokteran Gigi", "score": 730.0},
            {"name": "Ilmu Hukum", "score": 710.2},
            {"name": "Ilmu Komputer", "score": 735.8},
            {"name": "Manajemen", "score": 720.0},
            {"name": "Akuntansi", "score": 715.4},
            {"name": "Teknik Industri", "score": 700.1},
            {"name": "Psikologi", "score": 690.5},
            {"name": "Ilmu Komunikasi", "score": 685.3},
            {"name": "Hubungan Internasional", "score": 695.0},
            {"name": "Teknik Sipil", "score": 680.2},
            {"name": "Farmasi", "score": 725.0},
            {"name": "Gizi", "score": 660.5},
            {"name": "Sistem Informasi", "score": 705.0},
            {"name": "Teknik Elektro", "score": 690.0},
        ],
    },
    {
        "id": "itb",
        "name": "Institut Teknologi Bandung",
        "programs": [
            {"name": "Teknik Informatika", "score": 760.0},
            {"name": "Teknik Elektro", "score": 745.2},
            {"name": "Manajemen Rekayasa", "score": 730.5},
            {"name": "Teknik Kimia", "score": 720.4},
            {"name": "Teknik Sipil", "score": 705.8},
            {"name": "Arsitektur", "score": 695.1},
            {"name": "Teknik Perminyakan", "score": 750.0},
            {"name": "Teknik Mesin", "score": 715.3},
            {"name": "Teknik Lingkungan", "score": 685.6},
            {"name": "Desain Komunikasi Visual", "score": 710.0},
            {"name": "Teknik Geologi", "score": 690.0},
            {"name": "Matematika", "score": 670.5},
            {"name": "Fisika", "score": 665.0},
            {"name": "Kimia", "score": 660.2},
            {"name": "Desain Interior", "score": 685.0},
        ],
    },
    {
        "id": "ugm",
        "name": "Universitas Gadjah Mada",
        "programs": [
            {"name": "Kedokteran", "score": 740.0},
            {"name": "Kedokteran Gigi", "score": 720.5},
            {"name": "Teknologi Informasi", "score": 725.5},
            {"name": "Ilmu Hukum", "score": 705.3},
            {"name": "Manajemen", "score": 712.1},
            {"name": "Psikologi", "score": 695.0},
            {"name": "Hubungan Internasional", "score": 690.4},
            {"name": "Arsitektur", "score": 680.7},
            {"name": "Ilmu Komunikasi", "score": 675.2},
            {"name": "Kimia", "score": 660.0},
            {"name": "Pertanian", "score": 640.5},
            {"name": "Peternakan", "score": 610.8},
            {"name": "Teknik Sipil", "score": 690.0},
            {"name": "Teknik Mesin", "score": 685.5},
            {"name": "Farmasi", "score": 715.0},
        ],
    },
    {
        "id": "ipb",
        "name": "IPB University",
        "programs": [
            {"name": "Kedokteran Hewan", "score": 720.0},
            {"name": "Teknologi Pangan", "score": 685.5},
            {"name": "Manajemen", "score": 670.2},
            {"name": "Ilmu Komputer", "score": 690.8},
            {"name": "Agribisnis", "score": 640.1},
            {"name": "Teknik Sipil", "score": 625.4},
            {"name": "Biologi", "score": 615.0},
            {"name": "Ilmu Gizi", "score": 650.5},
            {"name": "Arsitektur Lanskap", "score": 630.2},
            {"name": "Teknik Industri", "score": 645.0},
            {"name": "Manajemen Sumberdaya Perairan", "score": 580.0},
            {"name": "Agronomi", "score": 600.5},
            {"name": "Ilmu Tanah", "score": 560.2},
            {"name": "Teknologi Hasil Hutan", "score": 575.0},
        ],
    },
    {
        "id": "its",
        "name": "Institut Teknologi Sepuluh Nopember",
        "programs": [
            {"name": "Teknik Informatika", "score": 720.5},
            {"name": "Sistem Informasi", "score": 700.2},
            {"name": "Teknik Industri", "score": 690.8},
            {"name": "Teknik Elektro", "score": 685.1},
            {"name": "Teknik Sipil", "score": 675.4},
            {"name": "Arsitektur", "score": 665.0},
            {"name": "Teknik Mesin", "score": 680.5},
            {"name": "Teknik Kimia", "score": 670.0},
            {"name": "Desain Produk", "score": 655.3},
            {"name": "Statistika", "score": 695.2},
            {"name": "Teknik Lingkungan", "score": 660.0},
            {"name": "Teknik Kelautan", "score": 645.5},
            {"name": "Teknik Fisika", "score": 650.0},
            {"name": "Matematika", "score": 640.2},
        ],
    },
    {
        "id": "unair",
        "name": "Universitas Airlangga",
        "programs": [
            {"name": "Kedokteran", "score": 735.0},
            {"name": "Kedokteran Gigi", "score": 710.5},
            {"name": "Ilmu Hukum", "score": 695.2},
            {"name": "Psikologi", "score": 680.1},
            {"name": "Kesehatan Masyarakat", "score": 660.8},
            {"name": "Manajemen", "score": 670.3},
            {"name": "Akuntansi", "score": 665.0},
            {"name": "Farmasi", "score": 715.0},
            {"name": "Ilmu Komunikasi", "score": 645.5},
            {"name": "Teknik Biomedis", "score": 690.0},
            {"name": "Ilmu Keperawatan", "score": 640.0},
            {"name": "Kedokteran Hewan", "score": 700.0},
        ],
    },
    {
        "id": "undip",
        "name": "Universitas Diponegoro",
        "programs": [
            {"name": "Kedokteran", "score": 715.4},
            {"name": "Kesehatan Masyarakat", "score": 645.2},
            {"name": "Teknik Sipil", "score": 630.0},
            {"name": "Teknik Mesin", "score": 625.8},
            {"name": "Ilmu Hukum", "score": 650.5},
            {"name": "Ilmu Komunikasi", "score": 640.1},
            {"name": "Informatika", "score": 680.2},
            {"name": "Akuntansi", "score": 655.7},
            {"name": "Manajemen", "score": 660.0},
            {"name": "Teknik Elektro", "score": 635.5},
            {"name": "Teknik Kimia", "score": 620.3},
            {"name": "Ilmu Gizi", "score": 610.8},
            {"name": "Psikologi", "score": 650.0},
            {"name": "Teknik Lingkungan", "score": 615.5},
            {"name": "Ilmu Kelautan", "score": 595.0},
        ],
    },
    {
        "id": "unpad",
        "name": "Universitas Padjadjaran",
        "programs": [
            {"name": "Pendidikan Dokter", "score": 720.1},
            {"name": "Psikologi", "score": 670.5},
            {"name": "Ilmu Komunikasi", "score": 665.8},
            {"name": "Ilmu Hukum", "score": 660.4},
            {"name": "Manajemen", "score": 655.0},
            {"name": "Akuntansi", "score": 645.3},
            {"name": "Teknik Informatika", "score": 675.2},
            {"name": "Hubungan Internasional", "score": 650.0},
            {"name": "Farmasi", "score": 700.5},
            {"name": "Perikanan", "score": 590.0},
            {"name": "Petermakan", "score": 575.5},
            {"name": "Kesehatan Masyarakat", "score": 630.0},
            {"name": "Ilmu Keperawatan", "score": 620.5},
        ],
    },
    {
        "id": "ub",
        "name": "Universitas Brawijaya",
        "programs": [
            {"name": "Kedokteran", "score": 718.5},
            {"name": "Teknik Informatika", "score": 685.0},
            {"name": "Ilmu Hukum", "score": 640.2},
            {"name": "Manajemen", "score": 635.8},
            {"name": "Teknik Industri", "score": 645.5},
            {"name": "Kesehatan Masyarakat", "score": 620.4},
            {"name": "Ilmu Komunikasi", "score": 630.1},
            {"name": "Administrasi Bisnis", "score": 625.6},
            {"name": "Agribisnis", "score": 605.0},
            {"name": "Teknik Sipil", "score": 650.0},
            {"name": "Psikologi", "score": 655.2},
            {"name": "Ilmu Kelautan", "score": 595.8},
            {"name": "Peternakan", "score": 590.0},
            {"name": "Teknologi Pangan", "score": 640.0},
            {"name": "Akuntansi", "score": 650.5},
        ],
    },
    {
        "id": "uns",
        "name": "Universitas Sebelas Maret",
        "programs": [
            {"name": "Kedokteran", "score": 710.2},
            {"name": "Informatika", "score": 670.8},
            {"name": "Teknik Sipil", "score": 625.5},
            {"name": "Ilmu Hukum", "score": 635.4},
            {"name": "Manajemen", "score": 630.1},
            {"name": "Psikologi", "score": 645.0},
            {"name": "Ilmu Komunikasi", "score": 620.8},
            {"name": "Pendidikan Dokter Gigi", "score": 695.3},
            {"name": "Akuntansi", "score": 640.5},
            {"name": "Teknik Mesin", "score": 615.2},
            {"name": "Teknik Industri", "score": 610.0},
            {"name": "Kesehatan Masyarakat", "score": 605.5},
            {"name": "Arsitektur", "score": 630.0},
            {"name": "Ilmu Gizi", "score": 600.0},
        ],
    },
    {
        "id": "unnes",
        "name": "Universitas Negeri Semarang",
        "programs": [
            {"name": "Pendidikan Guru Sekolah Dasar", "score": 580.5},
            {"name": "Manajemen", "score": 595.2},
            {"name": "Akuntansi", "score": 590.1},
            {"name": "Ilmu Hukum", "score": 605.8},
            {"name": "Teknik Informatika", "score": 620.4},
            {"name": "Kesehatan Masyarakat", "score": 585.5},
            {"name": "Pendidikan Bahasa Inggris", "score": 570.6},
            {"name": "Psikologi", "score": 610.0},
            {"name": "Ilmu Komunikasi", "score": 595.8},
            {"name": "Pendidikan Jasmani", "score": 550.2},
            {"name": "Matematika", "score": 575.0},
            {"name": "Kimia", "score": 560.5},
            {"name": "Pendidikan Biologi", "score": 565.0},
        ],
    },
    {
        "id": "upi",
        "name": "Universitas Pendidikan Indonesia",
        "programs": [
            {"name": "Pendidikan Guru Sekolah Dasar", "score": 590.2},
            {"name": "Psikologi", "score": 620.5},
            {"name": "Manajemen", "score": 610.8},
            {"name": "Ilmu Komunikasi", "score": 605.4},
            {"name": "Pendidikan Bahasa Inggris", "score": 585.1},
            {"name": "Ilmu Komputer", "score": 635.7},
            {"name": "Pendidikan Matematika", "score": 575.3},
            {"name": "Akuntansi", "score": 600.5},
            {"name": "Pendidikan Olahraga", "score": 545.0},
            {"name": "Pendidikan Biologi", "score": 570.0},
            {"name": "Pendidikan Kimia", "score": 565.5},
            {"name": "Pendidikan Seni", "score": 555.0},
        ],
    },
    {
        "id": "unhas",
        "name": "Universitas Hasanuddin",
        "programs": [
            {"name": "Pendidikan Dokter", "score": 705.4},
            {"name": "Kesehatan Masyarakat", "score": 615.2},
            {"name": "Teknik Informatika", "score": 655.8},
            {"name": "Ilmu Hukum", "score": 625.1},
            {"name": "Manajemen", "score": 620.5},
            {"name": "Teknik Sipil", "score": 610.4},
            {"name": "Kehutanan", "score": 580.6},
            {"name": "Ilmu Kelautan", "score": 590.0},
            {"name": "Farmasi", "score": 670.2},
            {"name": "Akuntansi", "score": 615.5},
            {"name": "Teknik Mesin", "score": 605.0},
            {"name": "Kedokteran Gigi", "score": 690.0},
            {"name": "Peternakan", "score": 570.5},
        ],
    },
    {
        "id": "telkom",
        "name": "Telkom University",
        "programs": [
            {"name": "Teknik Informatika", "score": 670.0},
            {"name": "Sistem Informasi", "score": 645.5},
            {"name": "Teknik Telekomunikasi", "score": 660.2},
            {"name": "Desain Komunikasi Visual", "score": 640.8},
            {"name": "Manajemen", "score": 620.1},
            {"name": "Akuntansi", "score": 610.5},
            {"name": "Ilmu Komunikasi", "score": 625.4},
            {"name": "Teknik Elektro", "score": 650.0},
            {"name": "Teknik Industri", "score": 635.3},
            {"name": "Teknik Fisika", "score": 625.0},
            {"name": "Desain Produk", "score": 615.5},
        ],
    },
    {
        "id": "usu",
        "name": "Universitas Sumatera Utara",
        "programs": [
            {"name": "Kedokteran", "score": 700.5},
            {"name": "Teknik Informatika", "score": 650.2},
            {"name": "Ilmu Hukum", "score": 620.8},
            {"name": "Manajemen", "score": 615.0},
            {"name": "Psikologi", "score": 630.5},
            {"name": "Teknik Sipil", "score": 605.4},
            {"name": "Farmasi", "score": 665.0},
            {"name": "Kesehatan Masyarakat", "score": 610.2},
            {"name": "Akuntansi", "score": 625.1},
            {"name": "Ilmu Komunikasi", "score": 600.5},
            {"name": "Teknik Mesin", "score": 610.0},
            {"name": "Teknik Elektro", "score": 615.5},
            {"name": "Kedokteran Gigi", "score": 685.0},
        ],
    },
    {
        "id": "unud",
        "name": "Universitas Udayana",
        "programs": [
            {"name": "Kedokteran", "score": 695.0},
            {"name": "Teknik Informatika", "score": 645.5},
            {"name": "Ilmu Hukum", "score": 610.2},
            {"name": "Manajemen", "score": 605.8},
            {"name": "Farmasi", "score": 655.0},
            {"name": "Kesehatan Masyarakat", "score": 590.4},
            {"name": "Teknik Sipil", "score": 595.1},
            {"name": "Ilmu Komunikasi", "score": 600.5},
            {"name": "Pendidikan Dokter Gigi", "score": 680.0},
            {"name": "Budaya", "score": 560.2},
            {"name": "Teknik Elektro", "score": 590.0},
            {"name": "Peternakan", "score": 565.5},
        ],
    },
    {
        "id": "unand",
        "name": "Universitas Andalas",
        "programs": [
            {"name": "Kedokteran", "score": 690.5},
            {"name": "Teknik Informatika", "score": 640.2},
            {"name": "Ilmu Hukum", "score": 605.8},
            {"name": "Manajemen", "score": 600.0},
            {"name": "Peternakan", "score": 560.5},
            {"name": "Farmasi", "score": 650.1},
            {"name": "Teknik Sipil", "score": 595.4},
            {"name": "Kesehatan Masyarakat", "score": 585.0},
            {"name": "Akuntansi", "score": 610.5},
            {"name": "Teknik Mesin", "score": 590.0},
            {"name": "Ilmu Komunikasi", "score": 595.0},
        ],
    },
    {
        "id": "unsri",
        "name": "Universitas Sriwijaya",
        "programs": [
            {"name": "Kedokteran", "score": 685.0},
            {"name": "Teknik Informatika", "score": 635.5},
            {"name": "Ilmu Hukum", "score": 600.2},
            {"name": "Manajemen", "score": 595.8},
            {"name": "Teknik Sipil", "score": 585.1},
            {"name": "Kesehatan Masyarakat", "score": 580.4},
            {"name": "Farmasi", "score": 640.0},
            {"name": "Akuntansi", "score": 605.5},
            {"name": "Ilmu Komunikasi", "score": 590.2},
            {"name": "Teknik Mesin", "score": 580.0},
            {"name": "Teknik Kimia", "score": 590.5},
            {"name": "Teknik Elektro", "score": 595.0},
        ],
    },
    {
        "id": "unmul",
        "name": "Universitas Mulawarman",
        "programs": [
            {"name": "Kedokteran", "score": 670.0},
            {"name": "Teknik Informatika", "score": 620.5},
            {"name": "Manajemen", "score": 585.2},
            {"name": "Ilmu Hukum", "score": 590.8},
            {"name": "Kehutanan", "score": 550.1},
            {"name": "Kesehatan Masyarakat", "score": 575.4},
            {"name": "Teknik Sipil", "score": 580.0},
            {"name": "Akuntansi", "score": 595.5},
            {"name": "Perikanan", "score": 555.0},
            {"name": "Peternakan", "score": 545.5},
        ],
    },
    {
        "id": "ulm",
        "name": "Universitas Lambung Mangkurat",
        "programs": [
            {"name": "Kedokteran", "score": 660.5},
            {"name": "Teknik Informatika", "score": 610.0},
            {"name": "Ilmu Hukum", "score": 580.2},
            {"name": "Manajemen", "score": 575.8},
            {"name": "Kesehatan Masyarakat", "score": 565.4},
            {"name": "Teknik Sipil", "score": 570.1},
            {"name": "Perikanan", "score": 540.0},
            {"name": "Akuntansi", "score": 585.5},
            {"name": "Agribisnis", "score": 555.2},
            {"name": "Peternakan", "score": 545.0},
        ],
    },
    {
        "id": "uny",
        "name": "Universitas Negeri Yogyakarta",
        "programs": [
            {"name": "Psikologi", "score": 635.5},
            {"name": "Manajemen", "score": 620.2},
            {"name": "Teknik Informatika", "score": 645.8},
            {"name": "Akuntansi", "score": 615.1},
            {"name": "Ilmu Komunikasi", "score": 610.4},
            {"name": "Pendidikan Guru Sekolah Dasar", "score": 590.0},
            {"name": "Pendidikan Bahasa Inggris", "score": 585.5},
            {"name": "Pendidikan Olahraga", "score": 560.2},
            {"name": "Pendidikan Seni", "score": 550.8},
            {"name": "Pendidikan Matematika", "score": 580.0},
            {"name": "Pendidikan Biologi", "score": 575.5},
            {"name": "Ilmu Hukum", "score": 605.0},
        ],
    },
    {
        "id": "unm",
        "name": "Universitas Negeri Makassar",
        "programs": [
            {"name": "Teknik Informatika", "score": 610.0},
            {"name": "Manajemen", "score": 585.5},
            {"name": "Akuntansi", "score": 580.2},
            {"name": "Ilmu Hukum", "score": 590.8},
            {"name": "Pendidikan Guru Sekolah Dasar", "score": 565.1},
            {"name": "Pendidikan Bahasa Inggris", "score": 555.4},
            {"name": "Psikologi", "score": 600.0},
            {"name": "Ilmu Komunikasi", "score": 575.5},
            {"name": "Pendidikan Matematika", "score": 560.0},
            {"name": "Teknik Sipil", "score": 570.0},
        ],
    },
    {
        "id": "untan",
        "name": "Universitas Tanjungpura",
        "programs": [
            {"name": "Kedokteran", "score": 650.0},
            {"name": "Teknik Informatika", "score": 600.5},
            {"name": "Ilmu Hukum", "score": 570.2},
            {"name": "Manajemen", "score": 565.8},
            {"name": "Kesehatan Masyarakat", "score": 555.4},
            {"name": "Teknik Sipil", "score": 560.1},
            {"name": "Akuntansi", "score": 575.0},
            {"name": "Kehutanan", "score": 540.5},
            {"name": "Perikanan", "score": 535.0},
            {"name": "Teknik Mesin", "score": 555.5},
        ],
    },
    {
        "id": "unpatti",
        "name": "Universitas Pattimura",
        "programs": [
            {"name": "Kedokteran", "score": 630.0},
            {"name": "Teknik Informatika", "score": 585.5},
            {"name": "Ilmu Hukum", "score": 560.2},
            {"name": "Manajemen", "score": 555.8},
            {"name": "Kesehatan Masyarakat", "score": 545.4},
            {"name": "Perikanan", "score": 530.1},
            {"name": "Teknik Sipil", "score": 550.0},
            {"name": "Akuntansi", "score": 565.5},
            {"name": "Peternakan", "score": 535.0},
        ],
    },
    {
        "id": "ung",
        "name": "Universitas Negeri Gorontalo",
        "programs": [
            {"name": "Teknik Informatika", "score": 580.0},
            {"name": "Manajemen", "score": 560.5},
            {"name": "Ilmu Hukum", "score": 555.2},
            {"name": "Pendidikan Guru Sekolah Dasar", "score": 545.8},
            {"name": "Kesehatan Masyarakat", "score": 550.4},
            {"name": "Akuntansi", "score": 565.1},
            {"name": "Ilmu Komunikasi", "score": 555.5},
            {"name": "Pendidikan Bahasa Inggris", "score": 540.0},
            {"name": "Pendidikan Olahraga", "score": 535.5},
        ],
    },
    {
        "id": "uinjkt",
        "name": "UIN Syarif Hidayatullah Jakarta",
        "programs": [
            {"name": "Kedokteran", "score": 670.0},
            {"name": "Teknik Informatika", "score": 620.5},
            {"name": "Manajemen", "score": 600.2},
            {"name": "Ilmu Hukum", "score": 595.8},
            {"name": "Psikologi", "score": 610.4},
            {"name": "Akuntansi", "score": 605.1},
            {"name": "Ilmu Komunikasi", "score": 590.0},
            {"name": "Pendidikan Bahasa Inggris", "score": 575.5},
            {"name": "Farmasi", "score": 630.0},
            {"name": "Pendidikan Guru Madrasah Ibtidaiyah", "score": 560.0},
        ],
    },
    {
        "id": "umm",
        "name": "Universitas Muhammadiyah Malang",
        "programs": [
            {"name": "Kedokteran", "score": 640.0},
            {"name": "Teknik Informatika", "score": 610.5},
            {"name": "Manajemen", "score": 585.2},
            {"name": "Ilmu Hukum", "score": 580.8},
            {"name": "Psikologi", "score": 595.4},
            {"name": "Akuntansi", "score": 590.1},
            {"name": "Ilmu Komunikasi", "score": 575.0},
            {"name": "Farmasi", "score": 620.0},
            {"name": "Teknik Sipil", "score": 580.0},
            {"name": "Pendidikan Bahasa Inggris", "score": 565.5},
        ],
    },
    {
        "id": "ums",
        "name": "Universitas Muhammadiyah Surakarta",
        "programs": [
            {"name": "Kedokteran", "score": 635.0},
            {"name": "Teknik Informatika", "score": 600.5},
            {"name": "Manajemen", "score": 575.2},
            {"name": "Ilmu Hukum", "score": 570.8},
            {"name": "Psikologi", "score": 585.4},
            {"name": "Akuntansi", "score": 580.1},
            {"name": "Ilmu Komunikasi", "score": 565.0},
            {"name": "Farmasi", "score": 610.0},
            {"name": "Teknik Sipil", "score": 575.0},
        ],
    },
    {
        "id": "unib",
        "name": "Universitas Bengkulu",
        "programs": [
            {"name": "Kedokteran", "score": 620.0},
            {"name": "Teknik Informatika", "score": 580.5},
            {"name": "Ilmu Hukum", "score": 555.2},
            {"name": "Manajemen", "score": 550.8},
            {"name": "Kesehatan Masyarakat", "score": 545.4},
            {"name": "Akuntansi", "score": 565.5},
            {"name": "Peternakan", "score": 530.0},
            {"name": "Teknik Sipil", "score": 555.1},
            {"name": "Perikanan", "score": 535.0},
        ],
    },
    {
        "id": "unram",
        "name": "Universitas Mataram",
        "programs": [
            {"name": "Kedokteran", "score": 645.0},
            {"name": "Teknik Informatika", "score": 595.5},
            {"name": "Ilmu Hukum", "score": 570.2},
            {"name": "Manajemen", "score": 565.8},
            {"name": "Kesehatan Masyarakat", "score": 555.4},
            {"name": "Teknik Sipil", "score": 560.1},
            {"name": "Akuntansi", "score": 575.0},
            {"name": "Peternakan", "score": 545.5},
            {"name": "Pendidikan Dokter Gigi", "score": 630.0},
            {"name": "Teknik Mesin", "score": 550.0},
        ],
    },
    {
        "id": "untad",
        "name": "Universitas Tadulako",
        "programs": [
            {"name": "Kedokteran", "score": 615.0},
            {"name": "Teknik Informatika", "score": 575.5},
            {"name": "Ilmu Hukum", "score": 550.2},
            {"name": "Manajemen", "score": 545.8},
            {"name": "Kesehatan Masyarakat", "score": 540.4},
            {"name": "Kehutanan", "score": 525.1},
            {"name": "Akuntansi", "score": 560.0},
            {"name": "Teknik Sipil", "score": 545.5},
            {"name": "Perikanan", "score": 530.0},
        ],
    },
    {
        "id": "unja",
        "name": "Universitas Jambi",
        "programs": [
            {"name": "Kedokteran", "score": 625.0},
            {"name": "Teknik Informatika", "score": 585.5},
            {"name": "Ilmu Hukum", "score": 560.2},
            {"name": "Manajemen", "score": 555.8},
            {"name": "Kesehatan Masyarakat", "score": 545.4},
            {"name": "Akuntansi", "score": 570.1},
            {"name": "Teknik Sipil", "score": 555.0},
            {"name": "Peternakan", "score": 535.5},
            {"name": "Kehutanan", "score": 540.0},
        ],
    },
    {
        "id": "unima",
        "name": "Universitas Negeri Manado",
        "programs": [
            {"name": "Teknik Informatika", "score": 570.0},
            {"name": "Manajemen", "score": 550.5},
            {"name": "Akuntansi", "score": 545.2},
            {"name": "Pendidikan Guru Sekolah Dasar", "score": 535.8},
            {"name": "Ilmu Hukum", "score": 555.4},
            {"name": "Pendidikan Bahasa Inggris", "score": 530.1},
            {"name": "Ilmu Komunikasi", "score": 545.0},
            {"name": "Pendidikan Olahraga", "score": 525.5},
        ],
    },
    {
        "id": "uinsa",
        "name": "UIN Sunan Ampel Surabaya",
        "programs": [
            {"name": "Manajemen", "score": 580.0},
            {"name": "Teknik Informatika", "score": 600.5},
            {"name": "Ilmu Hukum", "score": 570.2},
            {"name": "Psikologi", "score": 590.8},
            {"name": "Akuntansi", "score": 575.1},
            {"name": "Ilmu Komunikasi", "score": 565.4},
            {"name": "Pendidikan Bahasa Inggris", "score": 555.0},
            {"name": "Pendidikan Guru Madrasah Ibtidaiyah", "score": 545.0},
        ],
    },
    {
        "id": "unri",
        "name": "Universitas Riau",
        "programs": [
            {"name": "Kedokteran", "score": 660.0},
            {"name": "Teknik Informatika", "score": 610.5},
            {"name": "Ilmu Hukum", "score": 580.2},
            {"name": "Manajemen", "score": 575.8},
            {"name": "Kesehatan Masyarakat", "score": 565.4},
            {"name": "Teknik Sipil", "score": 570.1},
            {"name": "Akuntansi", "score": 585.5},
            {"name": "Perikanan", "score": 545.0},
            {"name": "Teknik Mesin", "score": 560.0},
            {"name": "Teknik Kimia", "score": 565.5},
        ],
    },
    {
        "id": "unila",
        "name": "Universitas Lampung",
        "programs": [
            {"name": "Kedokteran", "score": 655.0},
            {"name": "Teknik Informatika", "score": 605.5},
            {"name": "Ilmu Hukum", "score": 575.2},
            {"name": "Manajemen", "score": 570.8},
            {"name": "Kesehatan Masyarakat", "score": 560.4},
            {"name": "Teknik Sipil", "score": 565.1},
            {"name": "Akuntansi", "score": 580.0},
            {"name": "Peternakan", "score": 540.5},
            {"name": "Teknik Mesin", "score": 555.0},
            {"name": "Teknik Elektro", "score": 560.5},
        ],
    },
    {
        "id": "unej",
        "name": "Universitas Jember",
        "programs": [
            {"name": "Kedokteran", "score": 650.0},
            {"name": "Teknik Informatika", "score": 600.5},
            {"name": "Ilmu Hukum", "score": 570.2},
            {"name": "Manajemen", "score": 565.8},
            {"name": "Kesehatan Masyarakat", "score": 555.4},
            {"name": "Teknik Sipil", "score": 560.1},
            {"name": "Akuntansi", "score": 575.0},
            {"name": "Peternakan", "score": 540.5},
            {"name": "Pertanian", "score": 550.0},
            {"name": "Farmasi", "score": 620.0},
        ],
    },
    {
        "id": "unsrat",
        "name": "Universitas Sam Ratulangi",
        "programs": [
            {"name": "Kedokteran", "score": 660.0},
            {"name": "Teknik Informatika", "score": 610.5},
            {"name": "Ilmu Hukum", "score": 580.2},
            {"name": "Manajemen", "score": 575.8},
            {"name": "Kesehatan Masyarakat", "score": 565.4},
            {"name": "Teknik Sipil", "score": 570.1},
            {"name": "Akuntansi", "score": 585.5},
            {"name": "Perikanan", "score": 545.0},
            {"name": "Peternakan", "score": 550.0},
            {"name": "Farmasi", "score": 630.0},
        ],
    },
    {
        "id": "upnvj",
        "name": "UPN Veteran Jakarta",
        "programs": [
            {"name": "Kedokteran", "score": 670.0},
            {"name": "Teknik Informatika", "score": 620.5},
            {"name": "Manajemen", "score": 595.2},
            {"name": "Ilmu Hukum", "score": 590.8},
            {"name": "Kesehatan Masyarakat", "score": 580.4},
            {"name": "Akuntansi", "score": 605.1},
            {"name": "Ilmu Komunikasi", "score": 585.0},
            {"name": "Sistem Informasi", "score": 610.0},
            {"name": "Teknik Industri", "score": 595.5},
        ],
    },
    {
        "id": "upnyk",
        "name": "UPN Veteran Yogyakarta",
        "programs": [
            {"name": "Teknik Informatika", "score": 615.5},
            {"name": "Manajemen", "score": 590.2},
            {"name": "Akuntansi", "score": 585.8},
            {"name": "Ilmu Komunikasi", "score": 580.4},
            {"name": "Teknik Industri", "score": 595.0},
            {"name": "Sistem Informasi", "score": 605.0},
            {"name": "Ilmu Hukum", "score": 595.0},
            {"name": "Agroteknologi", "score": 555.0},
        ],
    },
    {
        "id": "upnjatim",
        "name": "UPN Veteran Jawa Timur",
        "programs": [
            {"name": "Teknik Informatika", "score": 610.0},
            {"name": "Manajemen", "score": 585.5},
            {"name": "Akuntansi", "score": 580.2},
            {"name": "Ilmu Hukum", "score": 575.8},
            {"name": "Teknik Industri", "score": 590.0},
            {"name": "Sistem Informasi", "score": 600.0},
            {"name": "Agroteknologi", "score": 550.0},
            {"name": "Teknik Kimia", "score": 580.0},
        ],
    },
    {
        "id": "utm",
        "name": "Universitas Trunojoyo Madura",
        "programs": [
            {"name": "Teknik Informatika", "score": 585.0},
            {"name": "Manajemen", "score": 560.5},
            {"name": "Akuntansi", "score": 555.2},
            {"name": "Ilmu Hukum", "score": 565.8},
            {"name": "Sistem Informasi", "score": 575.0},
            {"name": "Teknik Sipil", "score": 555.0},
            {"name": "Agribisnis", "score": 540.0},
        ],
    },
    {
        "id": "binus",
        "name": "Bina Nusantara University",
        "programs": [
            {"name": "Computer Science", "score": 660.0},
            {"name": "Information Systems", "score": 635.5},
            {"name": "Management", "score": 615.2},
            {"name": "Accounting", "score": 610.8},
            {"name": "Visual Communication Design", "score": 625.4},
            {"name": "Business Management", "score": 620.1},
            {"name": "Digital Business", "score": 640.0},
            {"name": "Psychology", "score": 630.5},
            {"name": "Communication Science", "score": 610.0},
            {"name": "Industrial Engineering", "score": 625.0},
        ],
    },
    {
        "id": "trisakti",
        "name": "Universitas Trisakti",
        "programs": [
            {"name": "Teknik Informatika", "score": 620.0},
            {"name": "Manajemen", "score": 595.5},
            {"name": "Akuntansi", "score": 590.2},
            {"name": "Ilmu Hukum", "score": 585.8},
            {"name": "Teknik Sipil", "score": 590.0},
            {"name": "Teknik Mesin", "score": 580.5},
            {"name": "Arsitektur", "score": 605.0},
            {"name": "Desain Komunikasi Visual", "score": 610.0},
            {"name": "Psikologi", "score": 600.0},
            {"name": "Ilmu Komunikasi", "score": 585.0},
        ],
    },
    {
        "id": "untar",
        "name": "Universitas Tarumanagara",
        "programs": [
            {"name": "Teknik Informatika", "score": 615.0},
            {"name": "Manajemen", "score": 590.5},
            {"name": "Akuntansi", "score": 585.2},
            {"name": "Ilmu Hukum", "score": 580.8},
            {"name": "Psikologi", "score": 595.0},
            {"name": "Arsitektur", "score": 600.0},
            {"name": "Desain Komunikasi Visual", "score": 605.0},
            {"name": "Ilmu Komunikasi", "score": 580.0},
        ],
    },
    {
        "id": "gunadarma",
        "name": "Universitas Gunadarma",
        "programs": [
            {"name": "Teknik Informatika", "score": 630.0},
            {"name": "Sistem Informasi", "score": 610.5},
            {"name": "Manajemen", "score": 600.2},
            {"name": "Akuntansi", "score": 595.8},
            {"name": "Teknik Elektro", "score": 605.0},
            {"name": "Teknik Sipil", "score": 595.0},
            {"name": "Psikologi", "score": 610.0},
            {"name": "Ilmu Komunikasi", "score": 590.0},
            {"name": "Desain Komunikasi Visual", "score": 605.5},
        ],
    },
    {
        "id": "mercubuana",
        "name": "Universitas Mercu Buana",
        "programs": [
            {"name": "Teknik Informatika", "score": 595.0},
            {"name": "Manajemen", "score": 575.5},
            {"name": "Akuntansi", "score": 570.2},
            {"name": "Ilmu Komunikasi", "score": 565.8},
            {"name": "Teknik Elektro", "score": 580.0},
            {"name": "Teknik Sipil", "score": 575.0},
            {"name": "Desain Komunikasi Visual", "score": 585.0},
            {"name": "Psikologi", "score": 580.0},
        ],
    },
    {
        "id": "uph",
        "name": "Universitas Pelita Harapan",
        "programs": [
            {"name": "Kedokteran", "score": 680.0},
            {"name": "Teknik Informatika", "score": 630.5},
            {"name": "Manajemen", "score": 610.2},
            {"name": "Akuntansi", "score": 605.8},
            {"name": "Ilmu Hukum", "score": 600.0},
            {"name": "Psikologi", "score": 615.0},
            {"name": "Arsitektur", "score": 620.0},
            {"name": "Desain Komunikasi Visual", "score": 625.0},
            {"name": "Ilmu Komunikasi", "score": 605.0},
        ],
    },
    {
        "id": "esunggul",
        "name": "Universitas Esa Unggul",
        "programs": [
            {"name": "Kedokteran", "score": 640.0},
            {"name": "Teknik Informatika", "score": 600.5},
            {"name": "Manajemen", "score": 580.2},
            {"name": "Akuntansi", "score": 575.8},
            {"name": "Ilmu Hukum", "score": 570.0},
            {"name": "Psikologi", "score": 590.0},
            {"name": "Ilmu Komunikasi", "score": 580.0},
            {"name": "Desain Komunikasi Visual", "score": 595.0},
        ],
    },
    {
        "id": "uksw",
        "name": "Universitas Kristen Satya Wacana",
        "programs": [
            {"name": "Teknik Informatika", "score": 605.0},
            {"name": "Manajemen", "score": 580.5},
            {"name": "Akuntansi", "score": 575.2},
            {"name": "Ilmu Hukum", "score": 570.8},
            {"name": "Psikologi", "score": 590.0},
            {"name": "Desain Komunikasi Visual", "score": 595.0},
            {"name": "Teknik Sipil", "score": 570.0},
            {"name": "Pendidikan Bahasa Inggris", "score": 560.0},
        ],
    },
    {
        "id": "unikap",
        "name": "Universitas Katolik Parahyangan",
        "programs": [
            {"name": "Teknik Informatika", "score": 625.0},
            {"name": "Manajemen", "score": 600.5},
            {"name": "Akuntansi", "score": 595.2},
            {"name": "Ilmu Hukum", "score": 590.8},
            {"name": "Psikologi", "score": 605.0},
            {"name": "Arsitektur", "score": 615.0},
            {"name": "Teknik Sipil", "score": 595.0},
            {"name": "Ilmu Komunikasi", "score": 590.0},
            {"name": "Ekonomi Pembangunan", "score": 580.0},
        ],
    },
    {
        "id": "ubaya",
        "name": "Universitas Surabaya",
        "programs": [
            {"name": "Kedokteran", "score": 655.0},
            {"name": "Teknik Informatika", "score": 610.5},
            {"name": "Manajemen", "score": 590.2},
            {"name": "Akuntansi", "score": 585.8},
            {"name": "Psikologi", "score": 600.0},
            {"name": "Farmasi", "score": 630.0},
            {"name": "Ilmu Hukum", "score": 585.0},
            {"name": "Ilmu Komunikasi", "score": 575.0},
        ],
    },
    {
        "id": "uinsgd",
        "name": "UIN Sunan Gunung Djati Bandung",
        "programs": [
            {"name": "Teknik Informatika", "score": 605.0},
            {"name": "Manajemen", "score": 580.5},
            {"name": "Ilmu Hukum", "score": 575.2},
            {"name": "Psikologi", "score": 590.8},
            {"name": "Akuntansi", "score": 585.0},
            {"name": "Pendidikan Bahasa Inggris", "score": 565.0},
            {"name": "Ilmu Komunikasi", "score": 575.0},
            {"name": "Pendidikan Guru Madrasah Ibtidaiyah", "score": 555.0},
        ],
    },
    {
        "id": "uinmalang",
        "name": "UIN Maulana Malik Ibrahim Malang",
        "programs": [
            {"name": "Kedokteran", "score": 635.0},
            {"name": "Teknik Informatika", "score": 600.5},
            {"name": "Manajemen", "score": 580.2},
            {"name": "Psikologi", "score": 590.8},
            {"name": "Ilmu Hukum", "score": 575.0},
            {"name": "Akuntansi", "score": 585.0},
            {"name": "Farmasi", "score": 615.0},
            {"name": "Pendidikan Bahasa Inggris", "score": 565.0},
        ],
    },
    {
        "id": "uinwalisongo",
        "name": "UIN Walisongo Semarang",
        "programs": [
            {"name": "Manajemen", "score": 575.5},
            {"name": "Teknik Informatika", "score": 595.0},
            {"name": "Ilmu Hukum", "score": 570.2},
            {"name": "Psikologi", "score": 585.8},
            {"name": "Akuntansi", "score": 580.0},
            {"name": "Pendidikan Bahasa Inggris", "score": 560.0},
            {"name": "Ilmu Komunikasi", "score": 570.0},
        ],
    },
    {
        "id": "uinsuka",
        "name": "UIN Sunan Kalijaga Yogyakarta",
        "programs": [
            {"name": "Manajemen", "score": 585.0},
            {"name": "Teknik Informatika", "score": 605.5},
            {"name": "Ilmu Hukum", "score": 580.2},
            {"name": "Psikologi", "score": 595.8},
            {"name": "Akuntansi", "score": 590.0},
            {"name": "Pendidikan Bahasa Inggris", "score": 570.0},
            {"name": "Ilmu Komunikasi", "score": 580.0},
        ],
    },
    {
        "id": "upr",
        "name": "Universitas Palangka Raya",
        "programs": [
            {"name": "Kedokteran", "score": 610.0},
            {"name": "Teknik Informatika", "score": 570.5},
            {"name": "Ilmu Hukum", "score": 550.2},
            {"name": "Manajemen", "score": 545.8},
            {"name": "Kesehatan Masyarakat", "score": 540.4},
            {"name": "Akuntansi", "score": 560.0},
            {"name": "Kehutanan", "score": 530.0},
            {"name": "Perikanan", "score": 535.5},
            {"name": "Pertanian", "score": 540.0},
        ],
    },
    {
        "id": "umi",
        "name": "Universitas Muslim Indonesia",
        "programs": [
            {"name": "Kedokteran", "score": 625.0},
            {"name": "Teknik Informatika", "score": 585.5},
            {"name": "Manajemen", "score": 565.2},
            {"name": "Ilmu Hukum", "score": 560.8},
            {"name": "Akuntansi", "score": 575.0},
            {"name": "Teknik Sipil", "score": 565.0},
            {"name": "Farmasi", "score": 600.0},
            {"name": "Ilmu Komunikasi", "score": 560.0},
        ],
    },
    {
        "id": "unmer",
        "name": "Universitas Merdeka Malang",
        "programs": [
            {"name": "Teknik Informatika", "score": 575.0},
            {"name": "Manajemen", "score": 555.5},
            {"name": "Akuntansi", "score": 550.2},
            {"name": "Ilmu Hukum", "score": 560.8},
            {"name": "Psikologi", "score": 570.0},
            {"name": "Ilmu Komunikasi", "score": 560.0},
            {"name": "Teknik Sipil", "score": 555.0},
        ],
    },
    {
        "id": "ukp",
        "name": "Universitas Kristen Petra",
        "programs": [
            {"name": "Teknik Informatika", "score": 610.0},
            {"name": "Manajemen", "score": 585.5},
            {"name": "Akuntansi", "score": 580.2},
            {"name": "Arsitektur", "score": 600.0},
            {"name": "Desain Komunikasi Visual", "score": 605.0},
            {"name": "Psikologi", "score": 590.0},
            {"name": "Ilmu Komunikasi", "score": 580.0},
        ],
    },
]


async def seed():
    await init_db()
    AsyncSessionLocal = _get_sessionmaker()

    print("Menghapus data yang sudah ada...")
    async with AsyncSessionLocal() as session:
        await session.execute(Program.__table__.delete())
        await session.execute(University.__table__.delete())
        await session.commit()

    print("Menyimpan data universities...")
    async with AsyncSessionLocal() as session:
        for u in MOCK_UNIVERSITIES:
            uni = University(id=u["id"], name=u["name"], sources=["internal_mock"])
            session.add(uni)
            await session.flush()
            for p in u["programs"]:
                prog = Program(
                    university_id=uni.id,
                    name=p["name"],
                    score_text=str(p["score"]),
                    degree="S1",
                    score=p["score"],
                    source_count=1,
                )
                session.add(prog)
        await session.commit()

    print("Menyimpan admin credentials...")
    async with AsyncSessionLocal() as session:
        await _seed_admin(session)

    print("Seeding database fiktif berhasil!")


if __name__ == "__main__":
    asyncio.run(seed())
